name: Build & Deploy
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true
  NODE_OPTIONS: --max_old_space_size=8192

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn install
      - run: npm run build
      - run: npm run doc
      - run: rm -rf packages/docs/doc
      - run: mkdir -p packages/docs/doc
      - run: cp -r website/build/ packages/docs/doc

      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.8
        with:
          package-path: ./packages/core/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.7
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{ steps.create_tag.outputs.version }}
          filter-author: (renovate-bot|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'


      - name: Create Release
        uses: jaywcjlove/create-tag-action@v1.3.8
        with:
          package-path: ./packages/core/package.json
          release: true
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-native@${{steps.changelog.outputs.version}}/file/README.md) [![npm version](https://img.shields.io/npm/v/@uiw/react-native.svg)](https://www.npmjs.com/package/@uiw/react-native) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-native)](https://bundlephobia.com/result?p=@uiw/react-native@${{steps.changelog.outputs.version}})

            ${{ steps.changelog.outputs.compareurl }}

            ${{ steps.changelog.outputs.changelog }}

      - run: git status
      - name: 📦  @uiw/react-native publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/core/package.json

      - name: 📦  @uiw/react-native-doc publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/docs/package.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to uimjs.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN_UIM }}
          publish_dir: ./website/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: master
          external_repository: uimjs/uimjs.github.io
